// <auto-generated />
using System;
using EvidencijaRacunarskeOpreme.Tehnoloska.RadSaPodacima;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EvidencijaRacunarskeOpreme.Tehnoloska.Migrations
{
    [DbContext(typeof(DbContextBaza))]
    [Migration("20240406173855_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EvidencijaRacunarskeOpreme.Tehnoloska.Podaci.RacunarskaOprema", b =>
                {
                    b.Property<int>("IdKomponente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKomponente"));

                    b.Property<int>("CenaKomponente")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumProizvodnje")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModelKomponente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProizvodjacKomponente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZemljaPorekla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKomponente");

                    b.ToTable("racunarskaOprema");
                });
#pragma warning restore 612, 618
        }
    }
}
